#!/usr/bin/env bash
# World wide web

dns_records() {
	local domain="$1"
	local subdomain="$2"
	if [[ -z "$subdomain" ]]; then
		dig +short "$domain" www.lb-01.web-01.web-02 A
	else
		dig +short "$subdomain" + "." + "$domain"
	fi
}

if [[ $# -eq 1 ]]; then
	for subdomain in www lb-01 web-01 web-02; do
		result=$(dns_records "$1" "$subdomain")
		if [[ -n "$result" ]]; then
			echo "The subdomain [$subdomain] is a A record and points to $result"
		fi
	done
else
	result=$(fetch_dns_records "$1" "$2")
	if [[ -n "$result" ]]; then
		echo "The subdomain [$2] is a A record and points to $result"
	fi
fi
