#!/usr/bin/env bash
#install nginx web server

# Update package lists for upgrades and new package installations
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# start nginx
sudo service nginx start

# Create a simple index.html file with "Hello World!" in the default nginx root directory
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# set custom 404 page
echo "Ceci n'est pas une page" | sudo tee "/var/www/html/custom_404.html" > /dev/null

# create a new configuration file
sudo echo "server {
	listen 80;
	
	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	add_header X-Served-By $hostname;

	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /var/www/html;
		internal;
	}

	location = /redirect_me {
		return 301 http://duaalearn.tech/new_page;
	}
	
	location / {
		try_files $uri $uri/ =404;
	}

}" | sudo tee /etc/nginx/sites-available/new > /dev/null

# Enable the new configuration "link"
sudo ln -s /etc/nginx/sites-available/new /etc/nginx/sites-enabled/

# Reload nginx
sudo service nginx reload
