#!/usr/bin/env bash
#update package lists
apt-get update

# Install NGINX
apt-get install -y nginx

# Create a temporary NGINX configuration file
cat <<EOF > /tmp/nginx.conf
server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

# Start NGINX with the temporary configuration
nginx -c /tmp/nginx.conf

# Verify NGINX is listening on port 80
netstat -tuln | grep :80
