#!/usr/bin/env bash
#This script for process and PID file
trap 'echo "I hate the kill command"; rm -r /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -r /var/run/myscript.pid; exit' SIGQUIT
touch /var/run/myscript.pid
pid=$(pgrep -f /var/run/myscript.pid)
echo "$pid" > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
