#!/usr/bin/env bash
# Change your home IP

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1	localhost/127.0.0.2     localhost/' ~/hosts.new
sed -i 's/157.240.11.35     localhost/8.8.8.8     facebook.com/' ~/hosts.new
grep -q 'facebook.com' ~/hosts.new || echo '8.8.8.8     facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
