#!/usr/bin/env bash
#show attached ips

function display_active_ipv4_ips() {
    # Get the list of active IPv4 connections
    active_ips=$(netstat -ntp)
    # Iterate over each IP address
    for ip in $active_ips; do
        echo "$ip"
    done
}

# Call the function to display active IPv4 IPs
display_active_ipv4_ips
