#!/usr/bin/env bash
# solve curl: (52) Empty reply from server for holbertonschool/265-0 docker image
# note that this image already made index.html return "hello Holberton"
# this script must use after connecting to the container
service apache2 start
